animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print 'The first animal is at 0 and is a ', animals[1]
print 'The third animal is at 2 and is a ', animals[2]
print 'The first animal is at 0 and is a ', animals[0]
print 'The fouth animal is at 3 and is a ', animals[3]
print 'The fifth animal is at 4 and is a ', animals[4]
print 'The third animal is at 2 and is a ', animals[2]
print 'The sixth animal is at 5 and is a ', animals[5]
print 'The fifth animal is at 4 and is a ', animals[4]
